app/Http/routes.php
<?php

$langSegment = Request::segment(1);
$locale = '';
if ($langSegment == 'en') {
    \App::setLocale($langSegment);
    $locale = $langSegment;
}

Route::pattern('id', '[0-9]+');
Route::pattern('post', '[0-9]+');
Route::pattern('product', '[0-9]+');
Route::pattern('nutritive', '[0-9]+');


Route::group(['middleware' => 'web'], function () use ($locale) {
    Route::group(['prefix' => $locale], function ()  {
        Route::group(['namespace' => 'Front', 'as' => 'front.'], function () {
            // Route::get('/facebook/login', ['uses' => 'PageController@fbLogin', 'as' => 'page.fb-login']);
            // Route::get('/facebook/callback', ['uses' => 'PageController@fb', 'as' => 'page.fb']);
            Route::get('/', ['uses' => 'PageController@index', 'as' => 'page.index']);
            Route::get('/pavlaka', ['uses' => 'PageController@pavlaka', 'as' => 'page.pavlaka']);
            Route::get(trans('front/interface.menu.company.url'), ['uses' => 'PageController@history', 'as' => 'page.history']);



            Route::get(trans('front/interface.menu.news.url').'/{cat?}', ['uses' => 'PageController@news', 'as' => 'page.news']);
            Route::get(trans('front/interface.menu.news.url').'/{cat}/{slug}', ['uses' => 'PageController@showPost', 'as' => 'page.show-post']);
            // Route::get('/vesti', ['uses' => 'PageController@news', 'as' => 'page.paginate-posts']);
            // Route::get('/postovi', ['uses' => 'PageController@paginateHomeGrid', 'as' => 'page.paginate-home-grid']);

            Route::get(trans('front/interface.menu.products.url'), ['uses' => 'ProductController@index', 'as' => 'product.index']);
            Route::get(trans('front/interface.menu.products.url').'/{slug}', ['uses' => 'ProductController@show', 'as' => 'product.show']);
            Route::get(trans('front/interface.menu.products.url').'/nutritive/{id}', ['uses' => 'ProductController@showNutritive', 'as' => 'product.show-nutritive']);

            Route::get(trans('front/interface.menu.recipe.url').'/{cat?}', ['uses' => 'RecipeController@index', 'as' => 'kuhinjica.index']);
            // Route::get('/kuhinjica/paginate', ['uses' => 'RecipeController@paginate', 'as' => 'kuhinjica.paginate']);
            Route::get(trans('front/interface.menu.recipe.url').'/{cat}/{slug}', ['uses' => 'RecipeController@show', 'as' => 'kuhinjica.show']);

            Route::get(trans('front/interface.menu.reports.url'), ['uses' => 'PageController@reports', 'as' => 'page.reports']);
            Route::get(trans('front/interface.menu.certificates.url'), ['uses' => 'PageController@certificates', 'as' => 'page.certificates']);
            Route::get(trans('front/interface.menu.faq.url'), ['uses' => 'PageController@faq', 'as' => 'page.faq']);
            Route::get(trans('front/interface.menu.contact.url'), ['uses' => 'PageController@showContact', 'as' => 'page.contact']);
            Route::post('/kontakt', ['uses' => 'PageController@contactUs', 'as' => 'page.contact-us']);

            Route::get('/junior', ['uses' => 'PageController@junior', 'as' => 'page.junior']);
            Route::get('/maslac', ['uses' => 'PageController@maslac', 'as' => 'page.maslac']);
            Route::get('/jogood-page', ['uses' => 'PageController@jogood', 'as' => 'page.jogood']);

            Route::get('/404', ['uses' => 'PageController@error404', 'as' => 'page.error404']);

            Route::get(trans('front/interface.menu.company.url').'/{slug}', ['uses' => 'PageController@showCompany', 'as' => 'company.show']);

            // Route::get('/fetchig/ew4we0-32_ewqnFDSfewroi3', 'SocialController@fetchInstagram');
            // Route::get('/fetchfb/ew4we0-32_ewqnFDSfewroi3', 'SocialController@fetchFacebook');
        });
    });

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

        Route::get('/login', ['uses' => 'AuthController@login', 'as' => 'admin.auth.login']);
        Route::post('/login', ['uses' => 'AuthController@postLogin', 'as' => 'admin.auth.post-login']);
        Route::get('/logout', ['uses' => 'AuthController@logout', 'as' => 'admin.auth.logout']);

        Route::group(['middleware' => 'auth'], function () {
            Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'admin.dashboard.index']);

            Route::get('/update-profile', ['uses' => 'AdministratorController@editProfile', 'as' => 'admin.administrator.edit-profile']);
            Route::put('/update-profile', ['uses' => 'AdministratorController@updateProfile', 'as' => 'admin.administrator.update-profile']);

            Route::post('/administrator/change-status', ['uses' => 'AdministratorController@changeState', 'as' => 'admin.administrator.change-status']);
            Route::resource('administrator', 'AdministratorController');



            // Route::post('/recipe-author/change-status', ['uses' => 'RecipeAuthorController@changeState', 'as' => 'admin.recipe-author.change-status']);
            // Route::resource('recipe-author', 'RecipeAuthorController');

            Route::post('/recipe/change-status', ['uses' => 'RecipeController@changeState', 'as' => 'admin.recipe.change-status']);
            Route::put('/recipe/reorder', ['uses' => 'RecipeController@reorder', 'as' => 'admin.recipe.reorder']);
            Route::resource('recipe', 'RecipeController');

            Route::post('/post/change-status', ['uses' => 'PostController@changeState', 'as' => 'admin.post.change-status']);
            Route::post('/post/slugify', ['uses' => 'PostController@slugify', 'as' => 'admin.post.slugify']);
            Route::put('/post/reorder', ['uses' => 'PostController@reorder', 'as' => 'admin.post.reorder']);
            Route::resource('post', 'PostController');

            // Route::get('/social-post/{type}', ['uses' => 'SocialPostController@index', 'as' => 'admin.social-post.index']);
            // Route::post('/social-post/change-status', ['uses' => 'SocialPostController@changeState', 'as' => 'admin.social-post.change-status']);
            // Route::delete('/social-post/{id}', ['uses' => 'SocialPostController@destroy', 'as' => 'admin.social-post.destroy']);
            Route::post('/certificate/change-status', ['uses' => 'CertificateController@changeState', 'as' => 'admin.certificate.change-status']);
            Route::put('/certificate/reorder', ['uses' => 'CertificateController@reorder', 'as' => 'admin.certificate.reorder']);
            Route::resource('certificate', 'CertificateController');


            Route::post('/post-photo/{id}', ['uses' => 'PostPhotoController@store', 'as' => 'admin.post-photo.store']);
            // Route::put('/post-photo/{id}/cover', ['uses' => 'PostPhotoController@updateCover', 'as' => 'admin.post-photo.cover']);
            Route::put('/post-photo/change-status', ['uses' => 'PostPhotoController@changeState', 'as' => 'admin.post-photo.change-status']);
            Route::put('/post-photo/reorder', ['uses' => 'PostPhotoController@reorder', 'as' => 'admin.post-photo.reorder']);
            Route::delete('/post-photo/{id}', ['uses' => 'PostPhotoController@destroy', 'as' => 'admin.post-photo.destroy']);

            Route::get('/brand', ['uses' => 'BrandController@index', 'as' => 'admin.brand.index']);
            Route::get('/brand/create', ['uses' => 'BrandController@create', 'as' => 'admin.brand.create']);
            Route::post('/brand/store', ['uses' => 'BrandController@store', 'as' => 'admin.brand.store']);
            Route::post('/brand/change-status', ['uses' => 'BrandController@changeState', 'as' => 'admin.brand.change-status']);
            Route::put('/brand/reorder', ['uses' => 'BrandController@reorder', 'as' => 'admin.brand.reorder']);
            Route::get('/brand/{brand}/edit', ['uses' => 'BrandController@edit', 'as' => 'admin.brand.edit']);
            Route::put('/brand/{brand}', ['uses' => 'BrandController@update', 'as' => 'admin.brand.update']);
            Route::delete('/brand/{brand}', ['uses' => 'BrandController@destroy', 'as' => 'admin.brand.destroy']);

            Route::post('/product/change-status', ['uses' => 'ProductController@changeState', 'as' => 'admin.product.change-status']);
            Route::put('/product/reorder', ['uses' => 'ProductController@reorder', 'as' => 'admin.product.reorder']);
            Route::post('/product/slugify', ['uses' => 'ProductController@slugify', 'as' => 'admin.product.slugify']);
            Route::resource('product', 'ProductController');

            Route::resource('product/nutritive', 'Product\NutritiveController');

            Route::put('/product/packshot/change-status', ['uses' => 'Product\PackshotController@changeState', 'as' => 'admin.product.packshot.change-status']);
            Route::post('/product/packshot/{id}', ['uses' => 'Product\PackshotController@store', 'as' => 'admin.product.packshot.store']);
            Route::put('/product/packshot/{id}', ['uses' => 'Product\PackshotController@update', 'as' => 'admin.product.packshot.update']);
            Route::put('/product/packshot/reorder', ['uses' => 'Product\PackshotController@reorder', 'as' => 'admin.product.packshot.reorder']);
            Route::delete('/product/packshot/{id}', ['uses' => 'Product\PackshotController@destroy', 'as' => 'admin.product.packshot.destroy']);
            Route::post('/packshot/slugify', ['uses' => 'Product\PackshotController@slugify', 'as' => 'admin.packshot.slugify']);

            Route::post('/package/change-status', ['uses' => 'PackageController@changeState', 'as' => 'admin.package.change-status']);
            Route::put('/package/reorder', ['uses' => 'PackageController@reorder', 'as' => 'admin.package.reorder']);
            Route::resource('package', 'PackageController');

            Route::post('/report/change-status', ['uses' => 'ReportController@changeState', 'as' => 'admin.report.change-status']);
            Route::put('/report/reorder', ['uses' => 'ReportController@reorder', 'as' => 'admin.report.reorder']);

app/Http/Controllers/Front/PageController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Requests\ContactRequest;
use App\Http\Controllers\Controller;
use App\Repositories\Post\PostInterface;
use App\Repositories\PostCategory\PostCategoryInterface;
use App\Repositories\Slide\SlideInterface;
use App\Repositories\Recipe\RecipeInterface;
use App\Repositories\History\HistoryInterface;
use App\Repositories\Product\PackshotInterface;
use App\Repositories\Package\PackageInterface;
use App\Repositories\Company\CompanyInterface;
use App\Repositories\Report\ReportInterface;
use App\Repositories\Faq\FaqInterface;
use App\Repositories\Job\JobInterface;
use App\Repositories\Certificate\CertificateInterface;
// use SammyK\LaravelFacebookSdk\LaravelFacebookSdk;
use App\Services\Mailers\ContactMailer;
use App\StaticContent;
use App\Services\File\Document as DocumentService;

class PageController extends Controller
{
    protected $post;
    protected $instagram;

    public function __construct(PostInterface $post)
    {
        $this->post = $post;
    }
    /**
     * Display front page
     *
     * @return \Illuminate\Http\Response
     */
    public function index(SlideInterface $slide, PackageInterface $package, StaticContent $content)
    {
        $slides = $slide->getForFront();
        // $recentPosts = $this->post->categoriesRecent();
        // $recentRecipes = $recipe->recent(5);

        $recentPosts = $this->post->recent(5);

        $packages = $package->recent(5);
        // dd($packages);
        $bodyClass = 'index';

        return view('front.page.index', compact('slides', 'packages','recentPosts', 'bodyClass'));
    }

    public function pavlaka()
    {
        $bodyClass = 'pavlaka-bg';
        return view('front.pavlaka.index', compact('bodyClass'));
    }

    public function history(HistoryInterface $history, CompanyInterface $company)
    {
        $yearsArray = $history->getForFront();
        $listArray = $company->recent(4);
        return view('front.page.history', compact('yearsArray', 'listArray'));
    }


    public function news(PostCategoryInterface $category, $cat = null)
    {

        $posts = $this->post->getBySlug($cat);

        if(count($posts) < 1) {
            $posts = $this->post->paginate();
        }

        $categories = $category->listCategories();
        return view('front.page.news.index', compact('posts', 'categories'));
    }

    public function showPost($cat, $slug)
    {
        $post = $this->post->findBySlug($slug);

        $id = ['id' => $post->id];
        $recentPosts = $this->post->recent(5, $id);
        return view('front.page.news.show', compact('post','recentPosts'));
    }

    public function paginatePosts()
    {
        $recentPosts = $this->post->recent(4);
        $content = '';
        foreach ($recentPosts as $post) {
            $content .= view('front.layout._partials.post.news', compact('post'))->render();
        }
        $next = $recentPosts->setPath(route('front.page.paginate-posts'))->nextPageUrl();
        return compact('content', 'next');
    }

    public function paginateHomeGrid(RecipeInterface $recipe)
    {
        $recentPosts = $this->post->categoriesRecent();
        $recentRecipes = $recipe->recent(5);
        $content = '';
        foreach ($recentPosts as $post) {
            $content .= view('front.layout._partials.post-grid', compact('recentPosts', 'recentRecipes'))->render();
        }
        $next = $recentPosts['news']->setPath(route('front.page.paginate-home-grid'))->nextPageUrl();
        return compact('content', 'next');
    }

    /**
     * Display privacy page
     *
     * @return \Illuminate\Http\Response
     */
    public function staticText(StaticPageInterface $page, $slug)
    {
        // $content = $page->findBySlug($slug);
        // $recent = $this->post->recent(4);

        return view('front.page.static-text', compact('content', 'recent'));
    }

    // get contact form
    public function showContact(JobInterface $job)
    {
        $jobs = $job->getActiveJobs();
        return view('front.page.contact', compact('jobs'));
    }


    // post contact form
    public function contactUs(Request $request, ContactMailer $mailer, DocumentService $document)
    {

        // try {
            
            $attachment = $request->file('file');
            $data = $request->all();
            $filename = null;
            if ($attachment) {
                $filename = $document->upload($attachment, config('settings.file.email'));
                $path = public_path().config('settings.file.email.upload_dir').$filename;
                $data['path'] = $path;
            }
            
            $mailer->sendContactMail($data);
            if ($filename) {
                $document->delete($filename, config('settings.file.email'));
            }

            return ['status' => 'success'];
        // } catch (\Exception $e) {
            dd($e);
            return ['status' => 'error'];
        // }
    }

    public function reports(ReportInterface $report)
    {
        $reports = $report->paginateForFront(30);
        return view('front.page.reports', compact('reports'));
    }

    public function faq(FaqInterface $faq)
    {
        $faqs = $faq->getOrdered();

        return view('front.page.faqs', compact('faqs'));
    }

    public function certificates(CertificateInterface $certificate)
    {
        $certificates = $certificate->paginateForFront(9);
        return view('front.page.certificates', compact('certificates'));
    }

    public function showCompany($slug, CompanyInterface $company)
    {
        $post = $company->findBySlug($slug);
        return view('front.page.company.show', compact('post'));
    }

    public function junior()
    {
        $bodyClass = 'junior-parallax';
        $footerClass = 'junior-footer';
        return view('front.junior.index', compact('bodyClass', 'footerClass'));
    }

    public function maslac()
    {
        $bodyClass = 'maslac-parallax';
        $footerClass = 'maslac-footer';
        return view('front.maslac.index', compact('bodyClass', 'footerClass'));
    }

    public function jogood() 
    {
        $bodyClass = 'jogood-parallax';
        $footerClass = 'jogood-footer';
        return view ('front.jogood.index', compact('bodyClass', 'footerClass'));
    }

    public function error404() {
        return view('errors.404');
    }


}

resources/views/front/jogood/index.blade.php
<?php $routeName = Route::currentRouteName(); ?>
<!DOCTYPE html>
<html lang="sr" class="{{ BrowserDetect::isMobile() ? 'mobile-device' : '' }}">
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-108928473-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-108928473-1');
    </script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <meta property="og:url"                content="{{ route('front.page.jogood') }}" />
    <meta property="og:type"               content="article" />
    <meta property="og:title"              content="Sve puca od voća! " />
    <meta property="og:description"        content="Osetite nezaboravnu senzaciju koja puca od voća!" />
    <meta property="og:image"              content="{{ url("") }}/assets/front/images/jogood/jogood-visual.jpg" />
    <meta property="fb:app_id"             content="162961914259939" />

    <link rel="shortcut icon" type="image/png" href="/assets/front/favicon.ico"/>
    <title>Imlek</title>

    @section('top_styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css">

    @show
    <link rel="stylesheet" href="/assets/front/css/main.css?asdf">

    <script>
        var csrf = '{{ csrf_token() }}';
        var basePath = '{{ url("") }}';
    </script>
</head>
<body class="jogood-bg">
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '162961914259939',
          xfbml      : true,
          version    : 'v2.10'
        });
        FB.AppEvents.logPageView();
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

    {{-- @include('front.layout._partials.mobile-header') --}}
    <scrollbar>

        <div id="barba-wrapper">

            <div class="barba-container">

                <header id="header" class="transparent-header">
                    <nav id="navigation">
                        <div class="pavlaka-logo">
                            <a href="{{ route('front.page.index') }}" class="no-barba">
                                <img src="/assets/front/images/logo.svg">
                            </a>
                        </div>
                    </nav>
                </header>

                <main id="jogood-page">
                    <section id="product-hero" class="product-jogood" data-product="jagoda">
                        <div class="wrap">
                            <div class="jogood-slider">
                                <div class="slider--item">
                                    <img src="/assets/front/images/jogood/sku/SKU-jagoda.png" alt="jogood">
                                    <span class="parallax-fruit">
                                        <img src="/assets/front/images/jogood/sku/jagode.png" data-depth="-0.1" class="fruit">
                                    </span>
                                </div>
                                <div class="slider--item">
                                    <img src="/assets/front/images/jogood/sku/SKU-kajsija.png" alt="jogood">
                                    <span class="parallax-fruit">
                                        <img src="/assets/front/images/jogood/sku/kajsije.png" data-depth="0.1" class="fruit">
                                    </span>
                                </div>
                                <div class="slider--item">
                                    <img src="/assets/front/images/jogood/sku/SKU-svoce.png" alt="jogood">
                                    <span class="parallax-fruit">
                                        <img src="/assets/front/images/jogood/sku/kupina.png" data-depth="-0.1" class="fruit">
                                    </span>
                                </div>
                                <div class="slider--item">
                                    <img src="/assets/front/images/jogood/sku/SKU-visnja.png" alt="jogood">
                                    <span class="parallax-fruit">
                                        <img src="/assets/front/images/jogood/sku/visnja.png" data-depth="0.1" class="fruit">
                                    </span>
                                </div>
                                <div class="slider--item">
                                    <img src="/assets/front/images/jogood/sku/SKU-nar.png" alt="jogood">
                                    <span class="parallax-fruit">
                                        <img src="/assets/front/images/jogood/sku/nar.png" data-depth="-0.1" class="fruit">
                                    </span>
                                </div>
                                <div class="slider--item">
                                    <img src="/assets/front/images/jogood/sku/SKU-ananas.png" alt="jogood">
                                    <span class="parallax-fruit">
                                        <img src="/assets/front/images/jogood/sku/ananas.png" data-depth="0.1" class="fruit">
                                    </span>
                                </div>
                                <div class="slider--item">
                                    <img src="/assets/front/images/jogood/sku/SKU-mango.png" alt="jogood">
                                    <span class="parallax-fruit">
                                        <img src="/assets/front/images/jogood/sku/mango.png" data-depth="0.1" class="fruit">
                                    </span>
                                </div>
                            </div>
                            <!--./slider-->
                            <div class="info-box">
                                <a href="/proizvodi/jogood#jogood-jagoda-330g" id="product-link" class="btn product-btn no-barba">Pogledaj više</a>
                                <div class="logo-hero">
                                    <img src="/assets/front/images/jogood/JGD-logo.png" alt="jogood">
                                </div>
                            </div>
                            <!--  ./info-box  -->
                            <div class="jogood-slider--buttons">
                                <button class="arrows-jogood arrows-jogood--next"></button>
                                <button class="arrows-jogood arrows-jogood--prev"></button>
                            </div>
                            <!--  ./jogood-slider--buttons  -->
                            <span class="parallax-span">
                                <img src="/assets/front/images/jogood/milk-hero-middle.png" class="slider-milk-splash" data-depth="0.1">
                                <div id="shape" data-depth="-0.1"></div>
                            </span>
                            <div class="parallax-bg">
                                <img src="/assets/front/images/jogood/milk-splash-hero.png" class="slider-milk-bg" data-depth="0.04">
                            </div>
                        </div>
                    </section>
                    <div id="fruit-prlx-wrap">
                        <section id="video">
                            <img src="/assets/front/images/jogood/wawe-yellow.png" alt="" class="wawe-yellow">
                            <img src="/assets/front/images/jogood/milk-splash.png" class="milk-splash">
                            <img src="/assets/front/images/jogood/green-bg.png" class="green-bg">
                            <div class="wrap">
                                <div class="hidden-text">
                                    <!--                                <h3>Sve puca od voća</h3>-->
                                    <img src="/assets/front/images/jogood/sve-puca.png" alt="">
                                    <p>Jogood je voćni jogurt bogat komadićima pažljivo biranih <br class="break">plodova voća koji pruža pun užitak u savršenom ukusu.</p> 
                                    <p>Savršena slatkoća komadića voća, koji se tope u svakom zalogaju,<br class="break"> izvor je čistog zadovoljstva. </p>
                                    <br>
                                    <p>Probajte i vi neodoljiv spoj jogurta I voća, idealnog <br class="break">kao osvežavajuća užina, zdraviji doručak</p>
                                    <p>ili dobro ohlađen desert. Osetite nezaboravnu <br class="break">senzaciju koja puca od voća!</p>
                                </div>
                                <video class="afterglow" id="jogood-video" width="1280" height="728" data-youtube-id="UMN6HfRtAss" data-volume=".5"></video>
                            </div>
                            <img src="/assets/front/images/jogood/jagoda-prlx.png" class="jagoda-prlx fruit-prlx">
                            <img src="/assets/front/images/jogood/ananas-prlx.png" class="ananas-prlx fruit-prlx">
                        </section>
                        <div class="splash-space">
                            <img src="/assets/front/images/jogood/kupina-prlx.png" class="kupina-prlx fruit-prlx">
                            <img src="/assets/front/images/jogood/visnja-prlx.png" class="visnja-prlx fruit-prlx">
                            <img src="/assets/front/images/jogood/kajsija-prlx.png" class="kajsija-prlx fruit-prlx">
                        </div>
                        <section id="jogood-footer">
                            
                            <img src="/assets/front/images/jogood/nar-prlx.png" class="nar-prlx fruit-prlx">
                            <div class="wrap">

                                <img src="/assets/front/images/jogood/JGD-logo.png">

                                <h3>Neka net puca<br>od voća</h3>

                                <div class="social">
                                    <a href="#" id="fb_jogood" class="icon"><svg class="fb"><use xlink:href="/assets/front/images/svg/store/sprite.svg#fb"></use></svg></a>
                                    <a href="#" id="in_jogood" class="icon"><svg class="in"><use xlink:href="/assets/front/images/svg/store/sprite.svg#in"></use></svg></a>
                                    <a href="#" id="tw_jogood" class="icon"><svg class="tw"><use xlink:href="/assets/front/images/svg/store/sprite.svg#tw"></use></svg></a>
                                </div>

                            </div>

                        </section>
                    </div>
                </main>

            </div>

        </div>

    </scrollbar>

    <div id="preload-page">
        <div id="preload-drop"></div>
    </div>
    <div id="page-between" style="display:none"></div>

    @section('bottom_scripts')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.js"></script>
    <script src="/assets/front/js/afterglow.min.js"></script>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>

    @show
    <script src="/assets/front/js/svg4everybody.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/4.13.0/bodymovin.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/parallax/3.1.0/parallax.min.js"></script>

    <script src="/assets/admin/js/jquery.cookie.js"></script>
    <script src="/assets/front/js/barba.min.js"></script>
    <script src="/assets/front/js/app.min.js"></script>
    <script src="/assets/admin/js/cookie.js"></script>
    <script src="/assets/admin/js/front-contact.js"></script>
    <script src="/assets/front/js/share.js"></script>

</body>
</html>