app/Http/routes.php
            Route::put('/recipe/reorder', ['uses' => 'RecipeController@reorder', 'as' => 'admin.recipe.reorder']);
            Route::resource('recipe', 'RecipeController');

            Route::post('/post/change-status', ['uses' => 'PostController@changeState', 'as' => 'admin.post.change-status']);
            Route::post('/post/slugify', ['uses' => 'PostController@slugify', 'as' => 'admin.post.slugify']);
            Route::put('/post/reorder', ['uses' => 'PostController@reorder', 'as' => 'admin.post.reorder']);
            Route::resource('post', 'PostController');

            // Route::get('/social-post/{type}', ['uses' => 'SocialPostController@index', 'as' => 'admin.social-post.index']);
            // Route::post('/social-post/change-status', ['uses' => 'SocialPostController@changeState', 'as' => 'admin.social-post.change-status']);
            // Route::delete('/social-post/{id}', ['uses' => 'SocialPostController@destroy', 'as' => 'admin.social-post.destroy']);
            Route::post('/certificate/change-status', ['uses' => 'CertificateController@changeState', 'as' => 'admin.certificate.change-status']);
            Route::put('/certificate/reorder', ['uses' => 'CertificateController@reorder', 'as' => 'admin.certificate.reorder']);
            Route::resource('certificate', 'CertificateController');


            Route::post('/post-photo/{id}', ['uses' => 'PostPhotoController@store', 'as' => 'admin.post-photo.store']);
            // Route::put('/post-photo/{id}/cover', ['uses' => 'PostPhotoController@updateCover', 'as' => 'admin.post-photo.cover']);
            Route::put('/post-photo/change-status', ['uses' => 'PostPhotoController@changeState', 'as' => 'admin.post-photo.change-status']);
            Route::put('/post-photo/reorder', ['uses' => 'PostPhotoController@reorder', 'as' => 'admin.post-photo.reorder']);
            Route::delete('/post-photo/{id}', ['uses' => 'PostPhotoController@destroy', 'as' => 'admin.post-photo.destroy']);

            Route::get('/brand', ['uses' => 'BrandController@index', 'as' => 'admin.brand.index']);
            Route::get('/brand/create', ['uses' => 'BrandController@create', 'as' => 'admin.brand.create']);
            Route::post('/brand/store', ['uses' => 'BrandController@store', 'as' => 'admin.brand.store']);
            Route::post('/brand/change-status', ['uses' => 'BrandController@changeState', 'as' => 'admin.brand.change-status']);
            Route::put('/brand/reorder', ['uses' => 'BrandController@reorder', 'as' => 'admin.brand.reorder']);
            Route::get('/brand/{brand}/edit', ['uses' => 'BrandController@edit', 'as' => 'admin.brand.edit']);
            Route::put('/brand/{brand}', ['uses' => 'BrandController@update', 'as' => 'admin.brand.update']);
            Route::delete('/brand/{brand}', ['uses' => 'BrandController@destroy', 'as' => 'admin.brand.destroy']);

            Route::post('/product/change-status', ['uses' => 'ProductController@changeState', 'as' => 'admin.product.change-status']);
            Route::put('/product/reorder', ['uses' => 'ProductController@reorder', 'as' => 'admin.product.reorder']);
            Route::post('/product/slugify', ['uses' => 'ProductController@slugify', 'as' => 'admin.product.slugify']);
            Route::resource('product', 'ProductController');

            Route::resource('product/nutritive', 'Product\NutritiveController');

            Route::put('/product/packshot/change-status', ['uses' => 'Product\PackshotController@changeState', 'as' => 'admin.product.packshot.change-status']);
            Route::post('/product/packshot/{id}', ['uses' => 'Product\PackshotController@store', 'as' => 'admin.product.packshot.store']);
            Route::put('/product/packshot/{id}', ['uses' => 'Product\PackshotController@update', 'as' => 'admin.product.packshot.update']);
            Route::put('/product/packshot/reorder', ['uses' => 'Product\PackshotController@reorder', 'as' => 'admin.product.packshot.reorder']);
            Route::delete('/product/packshot/{id}', ['uses' => 'Product\PackshotController@destroy', 'as' => 'admin.product.packshot.destroy']);
            Route::post('/packshot/slugify', ['uses' => 'Product\PackshotController@slugify', 'as' => 'admin.packshot.slugify']);

            Route::post('/package/change-status', ['uses' => 'PackageController@changeState', 'as' => 'admin.package.change-status']);
            Route::put('/package/reorder', ['uses' => 'PackageController@reorder', 'as' => 'admin.package.reorder']);
            Route::resource('package', 'PackageController');

            Route::post('/report/change-status', ['uses' => 'ReportController@changeState', 'as' => 'admin.report.change-status']);
            Route::put('/report/reorder', ['uses' => 'ReportController@reorder', 'as' => 'admin.report.reorder']);
            Route::resource('report', 'ReportController');

            Route::post('/job/change-status', ['uses' => 'JobController@changeState', 'as' => 'admin.job.change-status']);
            Route::resource('job', 'JobController');

            Route::post('/slide/change-status', ['uses' => 'SlideController@changeState', 'as' => 'admin.slide.change-status']);
            Route::put('/slide/reorder', ['uses' => 'SlideController@reorder', 'as' => 'admin.slide.reorder']);
            Route::resource('slide', 'SlideController');

            Route::post('/history/change-status', ['uses' => 'HistoryController@changeState', 'as' => 'admin.history.change-status']);
            Route::resource('history', 'HistoryController');

            Route::post('/faq/change-status', ['uses' => 'FaqController@changeState', 'as' => 'admin.faq.change-status']);
            Route::put('/faq/reorder', ['uses' => 'FaqController@reorder', 'as' => 'admin.faq.reorder']);
            Route::resource('faq', 'FaqController');

            Route::post('/recipe/change-status', ['uses' => 'RecipeController@changeState', 'as' => 'admin.recipe.change-status']);
            Route::post('/recipe/slugify', ['uses' => 'RecipeController@slugify', 'as' => 'admin.recipe.slugify']);
            Route::resource('recipe', 'RecipeController');

            Route::post('/recipe-category/change-status', ['uses' => 'RecipeCategoryController@changeState', 'as' => 'admin.recipe-category.change-status']);
            Route::resource('recipe-category', 'RecipeCategoryController');

            Route::post('/recipe-packshot/{id}', ['uses' => 'RecipePackshotController@store', 'as' => 'admin.recipe-packshot.store']);
            // Route::put('/recipe-packshot/{id}/cover', ['uses' => 'RecipePackshotController@updateCover', 'as' => 'admin.recipe-packshot.cover']);
            Route::put('/recipe-packshot/change-status', ['uses' => 'RecipePackshotController@changeState', 'as' => 'admin.recipe-packshot.change-status']);
            Route::put('/recipe-packshot/reorder', ['uses' => 'RecipePackshotController@reorder', 'as' => 'admin.recipe-packshot.reorder']);
            Route::delete('/recipe-packshot/{id}', ['uses' => 'RecipePackshotController@destroy', 'as' => 'admin.recipe-packshot.destroy']);

            Route::resource('company', 'CompanyController');

             Route::post('/company-packshot/{id}', ['uses' => 'CompanyPackshotController@store', 'as' => 'admin.company-packshot.store']);
            // Route::put('/company-packshot/{id}/cover', ['uses' => 'CompanyPackshotController@updateCover', 'as' => 'admin.company-packshot.cover']);
            Route::put('/company-packshot/change-status', ['uses' => 'CompanyPackshotController@changeState', 'as' => 'admin.company-packshot.change-status']);
            Route::put('/company-packshot/reorder', ['uses' => 'CompanyPackshotController@reorder', 'as' => 'admin.company-packshot.reorder']);
            Route::delete('/company-packshot/{id}', ['uses' => 'CompanyPackshotController@destroy', 'as' => 'admin.company-packshot.destroy']);


            // Route::get('/newsletter', ['uses' => 'NewsletterController@index', 'as' => 'admin.newsletter.index']);
            // Route::get('/newsletter/export', ['uses' => 'NewsletterController@export', 'as' => 'admin.newsletter.export']);

            // Route::get('/static/catalogue', ['uses' => 'StaticController@catalogue', 'as' => 'admin.static.catalogue']);
            // Route::put('/static/catalogue', ['uses' => 'StaticController@updateCatalogue', 'as' => 'admin.static.update-catalogue']);
            // Route::put('/static-page/{id}/edit', ['uses' => 'StaticPageController@update', 'as' => 'admin.static-page.update']);
        });
    });

    Route::group(['middleware' => 'auth'], function () {
        Route::get('laravel-filemanager', '\Tsawler\Laravelfilemanager\controllers\LfmController@show');
        Route::post('laravel-filemanager/upload', '\Tsawler\Laravelfilemanager\controllers\UploadController@upload');
        Route::get('laravel-filemanager/jsonimages', '\Tsawler\Laravelfilemanager\controllers\ItemsController@getImages');
        Route::get('laravel-filemanager/folders', '\Tsawler\Laravelfilemanager\controllers\FolderController@getFolders');
        Route::get('laravel-filemanager/newfolder', '\Tsawler\Laravelfilemanager\controllers\FolderController@getAddfolder');
        Route::get('laravel-filemanager/crop', '\Tsawler\Laravelfilemanager\controllers\CropController@getCrop');
        Route::get('laravel-filemanager/cropimage', '\Tsawler\Laravelfilemanager\controllers\CropController@getCropImage');
        Route::get('laravel-filemanager/resize', '\Tsawler\Laravelfilemanager\controllers\ResizeController@getResize');
        Route::get('laravel-filemanager/doresize', '\Tsawler\Laravelfilemanager\controllers\ResizeController@performResize');
        Route::get('laravel-filemanager/download', '\Tsawler\Laravelfilemanager\controllers\DownloadController@getDownload');
        Route::get('laravel-filemanager/delete', '\Tsawler\Laravelfilemanager\controllers\DeleteController@getDelete');

app/Job.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Job extends Model
{
    protected $table = 'jobs';

    protected $fillable = ['active'];

	public $timestamps = true;

    public function translations()
    {
        return $this->belongsToMany(Language::class, 'job_translations')
            ->withPivot('job_label');
    }
}

app/Http/Controllers/Admin/JobController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Repositories\Job\JobInterface;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class JobController extends BaseController
{


    protected $job;

    public function __construct(JobInterface $job)
    {
        $this->job = $job;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $listArray = $this->job->paginate();
        return view('admin.job.index', compact('listArray'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.job.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $data = $request->all();
            $job = $this->job->create($data);

            \Notification::success('Izvestaj je uspešno kreiran');
            return redirect(route('admin.job.edit', $job->id));
        } catch (\Exception $e) {
            \Notification::error('Dogodila se greška prilikom kreiranja izvestaja');
            return redirect(route('admin.job.index'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $job = $this->job->find($id);

        return view('admin.job.edit', compact('job'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {

            $data = $request->all();

            $this->job->update($id, $data);

            \Notification::success('Izvestaj je uspešno izmenjen');
        } catch (\Exception $e) {
            dd($e);
            \Notification::success('Dogodila se greška prilikom izmene izvestaja');
        }

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $job = $this->job->find($id);
        return $this->deleteItem($id, $this->job);
    }


    public function changeState(Request $request)
    {
        $job = $this->job->find($request->get('id'));
    
        return $this->changeStatus($this->job, $request);
    }
}

resources/views/admin/Job/create.blade.php
@extends('admin.layout.inner')

@section('bottom_scripts')
    @parent
    <script type="text/javascript" src="/assets/admin/plugins/form-jasnyupload/fileinput.min.js"></script>

@stop
@section('content')
    <div id="page-heading">
        <h1>Novi posao</h1>
        <div class="options">
            <a href="{{ route('admin.job.index') }}" class="btn btn-default-alt"><i class="fa fa-chevron-left"></i> Nazad</a>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-primary">
                    <form action="{{ route('admin.job.store') }}" method="post" enctype="multipart/form-data" class="form-horizontal">
                    {{ csrf_field() }}
                    <div class="panel-body">
                            
                        <div class="row">
                            <div class="col-sm-4">
                                <label for="job_label" class="upload-label">Pozicija</label>
                                {!! ml_input('text', $appLanguages, 'job_label', $errors) !!}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-lg-4">
                                <label for="active" class="col-sm-2 control-label">Aktivan</label>
                                <div class="checkbox block">
                                    <input type="hidden" name="active" value="0">
                                    <div class="toggle toggle-success form-active" title="Status"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6">
                                <button class="btn-primary btn">Snimi</button>
                                <a href="{{ route('admin.job.index') }}" class="btn btn-default-alt">Odustani</a>
                            </div>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/Job/edit.blade.php
@extends('admin.layout.inner')

@section('top_style')
    @parent
    <link rel="stylesheet" type="text/css" href="/assets/admin/plugins/jquery-fileupload/css/jquery.fileupload-ui.css">
    <link rel="stylesheet" type="text/css" href="/assets/admin/plugins/lightbox/css/lightbox.css">
@stop

@section('bottom_scripts')
    @parent
    <script type="text/javascript" src="/assets/admin/plugins/form-jasnyupload/fileinput.min.js"></script>

    <script type="text/javascript" src="/assets/admin/plugins/jquery-fileupload/js/jquery.iframe-transport.js"></script>
    <script type="text/javascript" src="/assets/admin/plugins/jquery-fileupload/js/jquery.fileupload.js"></script>
    <script type="text/javascript" src="/assets/admin/js/file-upload.js"></script>
    <script type="text/javascript" src="/assets/admin/plugins/lightbox/js/lightbox.min.js"></script>
@stop

@section('content')
    <div id="page-heading">
        <h1>Izmeni izvestaj</h1>
        <div class="options">
            <a href="{{ route('admin.job.index') }}" class="btn btn-default-alt"><i class="fa fa-chevron-left"></i> Nazad</a>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-primary">
                    <form action="{{ route('admin.job.update', $job) }}" method="post" enctype="multipart/form-data" class="form-horizontal">
                    {{ csrf_field() }}
                    {{ method_field('put') }}
                    <div class="panel-body">
                            
                        <div class="row">
                            <div class="col-sm-4">
                                <label for="job_label" class="upload-label">Naziv dokumenta</label>
                                {!! ml_input('text', $appLanguages, 'job_label', $errors, $job) !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-6 col-lg-4">
                                <label for="active" class="col-sm-2 control-label">Aktivan</label>
                                <div class="checkbox block">
                                    <input type="hidden" name="active" value="{{ $job->active }}">
                                    <div class="toggle toggle-success {{ $job->active ? 'active' : '' }} form-active" title="Status"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6">
                                <button class="btn-primary btn">Snimi</button>
                                <a href="{{ route('admin.job.index') }}" class="btn btn-default-alt">Odustani</a>
                            </div>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/Job/index.blade.php
@extends('admin.layout.inner')

@section('content')
    <div id="page-heading">
        <h1>Poslovi</h1>
        <div class="options">
            <a href="{{ route('admin.job.create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Novi posao</a>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-body resource-container" data-resource="job" data-modal="Da li ste sigurni da želite da obrišete izvestaj?">
                        @if(count($listArray))
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Naslov</th>
                                    <th class="col-lg-2 col-md-3">Datum kreiranja</th>
                                    <th class="col-lg-1 text-center">Aktivan</th>
                                    <th class="col-md-1 text-center">Opcije</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($listArray as $item)
                                <tr data-id="{{ $item->id }}">
                                    <td class="{{ $item->active ? '' : 'inactive' }}"><a href="{{ route('admin.job.edit', $item->id) }}">{{ $item->translations->find(1)->pivot->job_label }}</a></td>
                                    <td class="{{ $item->active ? '' : 'inactive' }}">{{ $item->created_at->format('d.m.Y H:i:s') }}</td>
                                    <td class="text-right table-options">
                                        <div class="col-sm-12">
                                            <div class="toggle toggle-success {{ $item->active ? 'active' : '' }} table-ajax" title="Status" data-id="{{ $item->id }}"></div>
                                        </div>
                                    </td>
                                    <td class="text-center">
                                        <div class="col-sm-6">
                                            <a href="{{ route('admin.job.edit', $item->id) }}" class="option-edit"><i class="fa fa-pencil"></i></a>
                                        </div>
                                        <div class="col-sm-6">
                                            <a class="delete-item"><i class="fa fa-times"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="text-center">{!! $listArray->render() !!}</div>
                        @else
                        <p class="text-center">Lista je trenutno prazna</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop