app/Http/routes.php
            Route::get(trans('front/interface.menu.company.url'), ['uses' => 'PageController@history', 'as' => 'page.history']);



            Route::get(trans('front/interface.menu.news.url').'/{cat?}', ['uses' => 'PageController@news', 'as' => 'page.news']);
            Route::get(trans('front/interface.menu.news.url').'/{cat}/{slug}', ['uses' => 'PageController@showPost', 'as' => 'page.show-post']);
            // Route::get('/vesti', ['uses' => 'PageController@news', 'as' => 'page.paginate-posts']);
            // Route::get('/postovi', ['uses' => 'PageController@paginateHomeGrid', 'as' => 'page.paginate-home-grid']);

            Route::get(trans('front/interface.menu.products.url'), ['uses' => 'ProductController@index', 'as' => 'product.index']);
            Route::get(trans('front/interface.menu.products.url').'/{slug}', ['uses' => 'ProductController@show', 'as' => 'product.show']);
            Route::get(trans('front/interface.menu.products.url').'/nutritive/{id}', ['uses' => 'ProductController@showNutritive', 'as' => 'product.show-nutritive']);

            Route::get(trans('front/interface.menu.recipe.url').'/{cat?}', ['uses' => 'RecipeController@index', 'as' => 'kuhinjica.index']);
            // Route::get('/kuhinjica/paginate', ['uses' => 'RecipeController@paginate', 'as' => 'kuhinjica.paginate']);
            Route::get(trans('front/interface.menu.recipe.url').'/{cat}/{slug}', ['uses' => 'RecipeController@show', 'as' => 'kuhinjica.show']);

            Route::get(trans('front/interface.menu.reports.url'), ['uses' => 'PageController@reports', 'as' => 'page.reports']);
            Route::get(trans('front/interface.menu.certificates.url'), ['uses' => 'PageController@certificates', 'as' => 'page.certificates']);
            Route::get(trans('front/interface.menu.faq.url'), ['uses' => 'PageController@faq', 'as' => 'page.faq']);
            Route::get(trans('front/interface.menu.contact.url'), ['uses' => 'PageController@showContact', 'as' => 'page.contact']);
            Route::post('/kontakt', ['uses' => 'PageController@contactUs', 'as' => 'page.contact-us']);

            Route::get('/junior', ['uses' => 'PageController@junior', 'as' => 'page.junior']);
            Route::get('/maslac', ['uses' => 'PageController@maslac', 'as' => 'page.maslac']);
            Route::get('/jogood-page', ['uses' => 'PageController@jogood', 'as' => 'page.jogood']);

            Route::get('/404', ['uses' => 'PageController@error404', 'as' => 'page.error404']);

            Route::get(trans('front/interface.menu.company.url').'/{slug}', ['uses' => 'PageController@showCompany', 'as' => 'company.show']);

            // Route::get('/fetchig/ew4we0-32_ewqnFDSfewroi3', 'SocialController@fetchInstagram');
            // Route::get('/fetchfb/ew4we0-32_ewqnFDSfewroi3', 'SocialController@fetchFacebook');
        });
    });

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {

        Route::get('/login', ['uses' => 'AuthController@login', 'as' => 'admin.auth.login']);
        Route::post('/login', ['uses' => 'AuthController@postLogin', 'as' => 'admin.auth.post-login']);
        Route::get('/logout', ['uses' => 'AuthController@logout', 'as' => 'admin.auth.logout']);

        Route::group(['middleware' => 'auth'], function () {
            Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'admin.dashboard.index']);

            Route::get('/update-profile', ['uses' => 'AdministratorController@editProfile', 'as' => 'admin.administrator.edit-profile']);
            Route::put('/update-profile', ['uses' => 'AdministratorController@updateProfile', 'as' => 'admin.administrator.update-profile']);

            Route::post('/administrator/change-status', ['uses' => 'AdministratorController@changeState', 'as' => 'admin.administrator.change-status']);
            Route::resource('administrator', 'AdministratorController');



            // Route::post('/recipe-author/change-status', ['uses' => 'RecipeAuthorController@changeState', 'as' => 'admin.recipe-author.change-status']);
            // Route::resource('recipe-author', 'RecipeAuthorController');

            Route::post('/recipe/change-status', ['uses' => 'RecipeController@changeState', 'as' => 'admin.recipe.change-status']);
            Route::put('/recipe/reorder', ['uses' => 'RecipeController@reorder', 'as' => 'admin.recipe.reorder']);
            Route::resource('recipe', 'RecipeController');

            Route::post('/post/change-status', ['uses' => 'PostController@changeState', 'as' => 'admin.post.change-status']);
            Route::post('/post/slugify', ['uses' => 'PostController@slugify', 'as' => 'admin.post.slugify']);
            Route::put('/post/reorder', ['uses' => 'PostController@reorder', 'as' => 'admin.post.reorder']);
            Route::resource('post', 'PostController');

            // Route::get('/social-post/{type}', ['uses' => 'SocialPostController@index', 'as' => 'admin.social-post.index']);
            // Route::post('/social-post/change-status', ['uses' => 'SocialPostController@changeState', 'as' => 'admin.social-post.change-status']);
            // Route::delete('/social-post/{id}', ['uses' => 'SocialPostController@destroy', 'as' => 'admin.social-post.destroy']);
            Route::post('/certificate/change-status', ['uses' => 'CertificateController@changeState', 'as' => 'admin.certificate.change-status']);
            Route::put('/certificate/reorder', ['uses' => 'CertificateController@reorder', 'as' => 'admin.certificate.reorder']);
            Route::resource('certificate', 'CertificateController');


            Route::post('/post-photo/{id}', ['uses' => 'PostPhotoController@store', 'as' => 'admin.post-photo.store']);
            // Route::put('/post-photo/{id}/cover', ['uses' => 'PostPhotoController@updateCover', 'as' => 'admin.post-photo.cover']);
            Route::put('/post-photo/change-status', ['uses' => 'PostPhotoController@changeState', 'as' => 'admin.post-photo.change-status']);
            Route::put('/post-photo/reorder', ['uses' => 'PostPhotoController@reorder', 'as' => 'admin.post-photo.reorder']);
            Route::delete('/post-photo/{id}', ['uses' => 'PostPhotoController@destroy', 'as' => 'admin.post-photo.destroy']);

            Route::get('/brand', ['uses' => 'BrandController@index', 'as' => 'admin.brand.index']);
            Route::get('/brand/create', ['uses' => 'BrandController@create', 'as' => 'admin.brand.create']);
            Route::post('/brand/store', ['uses' => 'BrandController@store', 'as' => 'admin.brand.store']);
            Route::post('/brand/change-status', ['uses' => 'BrandController@changeState', 'as' => 'admin.brand.change-status']);
            Route::put('/brand/reorder', ['uses' => 'BrandController@reorder', 'as' => 'admin.brand.reorder']);
            Route::get('/brand/{brand}/edit', ['uses' => 'BrandController@edit', 'as' => 'admin.brand.edit']);
            Route::put('/brand/{brand}', ['uses' => 'BrandController@update', 'as' => 'admin.brand.update']);
            Route::delete('/brand/{brand}', ['uses' => 'BrandController@destroy', 'as' => 'admin.brand.destroy']);

            Route::post('/product/change-status', ['uses' => 'ProductController@changeState', 'as' => 'admin.product.change-status']);
            Route::put('/product/reorder', ['uses' => 'ProductController@reorder', 'as' => 'admin.product.reorder']);
            Route::post('/product/slugify', ['uses' => 'ProductController@slugify', 'as' => 'admin.product.slugify']);
            Route::resource('product', 'ProductController');

            Route::resource('product/nutritive', 'Product\NutritiveController');

            Route::put('/product/packshot/change-status', ['uses' => 'Product\PackshotController@changeState', 'as' => 'admin.product.packshot.change-status']);
            Route::post('/product/packshot/{id}', ['uses' => 'Product\PackshotController@store', 'as' => 'admin.product.packshot.store']);
            Route::put('/product/packshot/{id}', ['uses' => 'Product\PackshotController@update', 'as' => 'admin.product.packshot.update']);
            Route::put('/product/packshot/reorder', ['uses' => 'Product\PackshotController@reorder', 'as' => 'admin.product.packshot.reorder']);
            Route::delete('/product/packshot/{id}', ['uses' => 'Product\PackshotController@destroy', 'as' => 'admin.product.packshot.destroy']);
            Route::post('/packshot/slugify', ['uses' => 'Product\PackshotController@slugify', 'as' => 'admin.packshot.slugify']);

            Route::post('/package/change-status', ['uses' => 'PackageController@changeState', 'as' => 'admin.package.change-status']);
            Route::put('/package/reorder', ['uses' => 'PackageController@reorder', 'as' => 'admin.package.reorder']);
            Route::resource('package', 'PackageController');

            Route::post('/report/change-status', ['uses' => 'ReportController@changeState', 'as' => 'admin.report.change-status']);
            Route::put('/report/reorder', ['uses' => 'ReportController@reorder', 'as' => 'admin.report.reorder']);
            Route::resource('report', 'ReportController');

            Route::post('/job/change-status', ['uses' => 'JobController@changeState', 'as' => 'admin.job.change-status']);
            Route::resource('job', 'JobController');

            Route::post('/slide/change-status', ['uses' => 'SlideController@changeState', 'as' => 'admin.slide.change-status']);
            Route::put('/slide/reorder', ['uses' => 'SlideController@reorder', 'as' => 'admin.slide.reorder']);
            Route::resource('slide', 'SlideController');

            Route::post('/history/change-status', ['uses' => 'HistoryController@changeState', 'as' => 'admin.history.change-status']);
            Route::resource('history', 'HistoryController');

            Route::post('/faq/change-status', ['uses' => 'FaqController@changeState', 'as' => 'admin.faq.change-status']);

app/Http/Controllers/Admin/AdministratorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Repositories\User\UserInterface;
use App\Repositories\User\Type\Administrator;
use App\Http\Requests\AdministratorRequest;
use App\Services\File\Image as ImageService;

class AdministratorController extends BaseController
{
    private $user;

    public function __construct(UserInterface $user)
    {
        $this->user = $user;

        // if (\Auth::user()->cannot('access')) {
        //     abort(403, "Pristup nije dozvoljen");
        // }

        // $this->authorize('access', \Auth::user());
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (\Auth::user()->cannot('access')) {
            abort(403, "Pristup nije dozvoljen");
        }

        $listArray = $this->user->paginateUsers(0);

        return view('admin.administrator.index', compact('listArray'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (\Auth::user()->cannot('access')) {
            abort(403, "Pristup nije dozvoljen");
        }

        return view('admin.administrator.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdministratorRequest $request)
    {
        if (\Auth::user()->cannot('access')) {
            abort(403, "Pristup nije dozvoljen");
        }

        try {
            $user = $this->user->create(new Administrator($request->all()));
            \Notification::success('Novi administrator je uspešno kreiran');
        } catch (\Exception $e) {
            dd($e);
            \Notification::error('Dogodila se greška prilikom kreiranja administratora');
        }

        return redirect(route('admin.administrator.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (\Auth::user()->cannot('access')) {
            abort(403, "Pristup nije dozvoljen");
        }

        $user = $this->user->find($id);
        return view('admin.administrator.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdministratorRequest $request, $id)
    {
        if (\Auth::user()->cannot('access')) {
            abort(403, "Pristup nije dozvoljen");
        }

        try {
            $this->user->update($id, new Administrator($request->all()));
            \Notification::success('Podaci administratora su uspešno izmenjeni');
        } catch (\Exception $e) {
            dd($e);
            \Notification::error('Dogodila se greška prilikom kreiranja administratora');
        }

        return redirect(route('admin.administrator.index'));
    }

    /**
     * Remove the specified user from storage.
     *
     * @param  int  $id
     * @return json
     */
    public function destroy($id)
    {
        if (\Auth::user()->cannot('access')) {
            abort(403, "Pristup nije dozvoljen");
        }

        return $this->deleteItem($id, $this->user);
    }

    /**
     * Method is changing active state of user
     *
     * @return json     information about changed state
     */
    public function changeState(Request $request)
    {
        if (\Auth::user()->cannot('access')) {
            abort(403, "Pristup nije dozvoljen");
        }

        return $this->changeStatus($this->user, $request);
    }

    public function editProfile()
    {
        $user = \Auth::user();
        $profile = true;

        if ($user->role == 0) {
            return view('admin.administrator.edit', compact('user'));
        } else {
            return view('admin.blogger.edit', compact('user', 'profile'));
        }
    }
}

resources/views/admin/administrator/create.blade.php
@extends('admin.layout.inner')

@section('content')
    <div id="page-heading">
        <h1>Administrator</h1>
        <div class="options">
            <a href="{{ URL::route('admin.administrator.index') }}" class="btn btn-default-alt"><i class="fa fa-chevron-left"></i> Nazad</a>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4>Novi administrator</h4>
                    </div>
                    {!! Form::open(['url' => route('admin.administrator.store'), 'method' => 'post', 'class' => 'form-horizontal']) !!}
                    <div class="panel-body">
                        <div class="form-group {{ error_class($errors, 'name') }}">
                            {!! Form::label('name', 'Ime', ['class' => 'col-sm-2 control-label']) !!}
                            <div class="col-sm-6 col-lg-4">
                                {!! Form::text('name', old('name'), ['class' => 'form-control', 'autofocus']) !!}
                                {!! validation_error($errors, 'name') !!}
                            </div>
                        </div>
                        <div class="form-group {{ error_class($errors, 'email') }}">
                            {!! Form::label('email', 'Email', ['class' => 'col-sm-2 control-label']) !!}
                            <div class="col-sm-6 col-lg-4">
                                {!! Form::email('email', old('email'), ['class' => 'form-control']) !!}
                                {!! validation_error($errors, 'email') !!}
                            </div>
                        </div>
                        <div class="form-group {{ error_class($errors, 'password') }}">
                            {!! Form::label('password', 'Lozinka', ['class' => 'col-sm-2 control-label']) !!}
                            <div class="col-sm-6 col-lg-4">
                                {!! Form::password('password', ['class' => 'form-control']) !!}
                                <p class="help-block">Lozinka mora da sadrži minimalno šest karaktera od kojih minimalno jedno veliko slovo, malo slovo i jedan broj</p>
                                {!! validation_error($errors, 'password') !!}
                            </div>
                        </div>
                        <div class="form-group {{ error_class($errors, 'password_confirmation') }}">
                            {!! Form::label('password_confirmation', 'Potvrdi lozinku', ['class' => 'col-sm-2 control-label']) !!}
                            <div class="col-sm-6 col-lg-4">
                                {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
                                {!! validation_error($errors, 'password_confirmation') !!}
                            </div>
                        </div>
                        <div class="form-group">
                            {!! Form::label('active', 'Aktivan', ['class' => 'col-sm-2 control-label']) !!}
                            <div class="col-sm-6 col-lg-4">
                                <div class="checkbox block">
                                    <input type="hidden" name="active" value="1">
                                    <div class="toggle toggle-success form-active" title="Status"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6">
                                <button class="btn-primary btn">Snimi</button>
                                <a href="{{ URL::route('admin.administrator.index') }}" class="btn btn-default-alt">Odustani</a>
                            </div>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/administrator/edit.blade.php
@extends('admin.layout.inner')

@section('content')
    <div id="page-heading">
        <h1>Administrator</h1>
        <div class="options">
            <a href="{{ URL::route('admin.administrator.index') }}" class="btn btn-default-alt"><i class="fa fa-chevron-left"></i> Nazad</a>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4>Izmena podataka</h4>
                    </div>
                    {!! Form::open(['url' => route('admin.administrator.update', $user->id), 'method' => 'put', 'class' => 'form-horizontal']) !!}
                    <div class="panel-body">
                        <div class="form-group {{ error_class($errors, 'name') }}">
                            {!! Form::label('name', 'Ime', ['class' => 'col-sm-2 control-label']) !!}
                            <div class="col-sm-6">
                                {!! Form::text('name', old('name', $user->name), ['class' => 'form-control', 'autofocus']) !!}
                                {!! validation_error($errors, 'name') !!}
                            </div>
                        </div>
                        <div class="form-group {{ error_class($errors, 'email') }}">
                            {!! Form::label('email', 'Email', ['class' => 'col-sm-2 control-label']) !!}
                            <div class="col-sm-6">
                                {!! Form::email('email', old('email', $user->email), ['class' => 'form-control', 'required']) !!}
                                {!! validation_error($errors, 'email') !!}
                            </div>
                        </div>
                        <div class="form-group {{ error_class($errors, 'password') }}">
                            {!! Form::label('password', 'Lozinka', ['class' => 'col-sm-2 control-label']) !!}
                            <div class="col-sm-6">
                                {!! Form::password('password', ['class' => 'form-control']) !!}
                                <p class="help-block">Lozinka mora da sadrži minimalno šest karaktera od kojih minimalno jedno veliko slovo, malo slovo i jedan broj</p>
                                {!! validation_error($errors, 'password') !!}
                            </div>
                        </div>
                        <div class="form-group {{ error_class($errors, 'password_confirmation') }}">
                            {!! Form::label('password_confirmation', 'Potvrda lozinke', ['class' => 'col-sm-2 control-label']) !!}
                            <div class="col-sm-6">
                                {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
                                {!! validation_error($errors, 'password_confirmation') !!}
                            </div>
                        </div>
                        @if(Auth::user()->id != $user->id)
                        <div class="form-group">
                            {!! Form::label('active', 'Aktivan', ['class' => 'col-sm-2 control-label']) !!}
                            <div class="col-sm-6">
                                <div class="checkbox block">
                                    <input type="hidden" name="active" value="{{ $user->active }}">
                                    <div class="toggle toggle-success {{ $user->active ? 'active' : '' }} form-active" title="{{ trans('admin/form.btn_status') }}"></div>
                                </div>
                            </div>
                        </div>
                        @else
                            <input type="hidden" name="active" value="1">
                        @endif
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-sm-6">
                                <button class="btn-primary btn">Snimi</button>
                                <a href="{{ route('admin.administrator.index') }}" class="btn btn-default-alt">Odustani</a>
                            </div>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/admin/administrator/index.blade.php
@extends('admin.layout.inner')

@section('content')
    <div id="page-heading">
        <h1>Administratori</h1>
        <div class="options">
            <a href="{{ URL::route('admin.administrator.create') }}" class="btn btn-success"><i class="fa fa-institution"></i> Novi administrator</a>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="panel panel-primary">
                    <div class="panel-body resource-container" data-resource="administrator" data-modal="Da li ste sigurni da želite da obrišete administratora?">
                        @if(count($listArray))
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Ime</th>
                                    <th>Email</th>
                                    <th class="col-md-1 text-center">Aktivan</th>
                                    <th class="col-md-1 text-center">Opcije</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($listArray as $item)
                                @if($item->id != Auth::user()->id)
                                <tr data-id="{{ $item->id }}">
                                    <td class="{{ $item->active ? '' : 'inactive' }}"><a href="{{ URL::route('admin.administrator.edit', $item->id) }}">{{ $item->name }}</a></td>
                                    <td class="{{ $item->active ? '' : 'inactive' }}"><a href="mailto:{{ $item->email }}" target="_blank">{{ $item->email }}</a></td>
                                    <td class="text-right table-options">
                                        <div class="toggle toggle-success {{ $item->active ? 'active' : '' }} table-ajax" title="{{ Lang::get('admin/form.btn_status') }}" data-id="{{ $item->id }}"></div>
                                    </td>
                                    <td class="text-center">
                                        <div class="col-sm-6">
                                        <a href="{{ URL::route('admin.administrator.edit', $item->id) }}" class="option-edit"><i class="fa fa-pencil"></i></a>
                                        </div>
                                        <div class="col-sm-6">
                                        <a class="delete-item"><i class="fa fa-times"></i> </a>
                                        </div>
                                    </td>
                                </tr>
                                @endif
                            @endforeach
                            </tbody>
                        </table>
                        <div class="text-center">{!! $listArray->render() !!}</div>
                        @else
                        <p class="text-center">Lista je trenutno prazna</p>
                        <p class="text-center">
                            <a href="{{ URL::route('admin.administrator.create') }}" class="btn">{{ trans('admin/user.add_administrator') }}</a>
                        </p>

                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@stop